image: $CI_REGISTRY_IMAGE:latest
services:
  - docker:dind

stages:
  - container
  - build
  - validate
  - test

before_script:
  - yarn install
  # - keytool -genkey -v -keystore ./android/app/debug.keystore -storepass android -alias androiddebugkey -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, S=Unknown, C=Unknown" -keypass android -keyalg RSA -keysize 2048 -validity 10000
  # - echo "sdk.dir=${ANDROID_HOME}" >>./android/local.properties

after_script:
  - rm ./android/local.properties && rm ./android/app/debug.keystore

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

variables:
  SAST_DEFAULT_ANALYZERS: "eslint,nodejs-scan,tslint"
  DS_DEFAULT_ANALYZERS: "gemnasium,retire.js"
  SAST_DISABLE_DIND: "false"
  DS_DISABLE_DIND: "false"

container:
  image: docker
  services:
    - docker:dind
  only:
    changes:
      - Dockerfile  
  stage: container
  before_script: []
  after_script: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

android_29:
  stage: build
  # when: manual
  before_script: []
  after_script: []
  script:
    - export PATH=/android-sdk-linux/tools:$PATH
    - export PATH=/android-sdk-linux/tools/bin:$PATH
    - export PATH=/android-sdk-linux/platform-tools:$PATH
    - ls
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker pull $CI_REGISTRY_IMAGE:q-google-x86 || true
    # - cd /android-emulator-container-scripts && source ./configure.sh
    # - emu-docker create emulator.zip system-image.zip --tag $CI_REGISTRY_IMAGE:q-google-x86
    # - docker build --cache-from $CI_REGISTRY_IMAGE:q-google-x86 --tag $CI_REGISTRY_IMAGE:q-google-x86 /android-emulator-container-scripts/src
    - docker run -d --device /dev/kvm --publish 8554:8554/tcp --publish 5555:5555/tcp $CI_REGISTRY_IMAGE:q-google-x86
    - ls /android-sdk-linux/platform-tools/
    - ls /root/
    - adb connect localhost:5555
    - docker push $CI_REGISTRY_IMAGE:q-google-x86

build:
  stage: build
  script:
    - cd android && ./gradlew :app:assemble -Dorg.gradle.daemon=true --stacktrace
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - android/build/
      - android/.gradle/
      - android/local.properties
      - android/app/build/
      - android/app/debug.keystore
      - node_modules/

java_checkstyle:
  stage: validate
  script:
    - cd android && ./gradlew :app:checkstyle
  artifacts:
    paths:
      - android/app/build/reports/checkstyle/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - android/build/
      - android/.gradle/
      - android/local.properties
      - android/app/build/
      - android/app/debug.keystore
      - node_modules/

typescript_eslint:
  stage: validate
  script:
    - node_modules/eslint/bin/eslint.js ./components/** ./hooks/** ./network/** ./screens/** ./App.tsx ./index.js ./Store.tsx
  allow_failure: true

code_quality:
  stage: validate
  before_script: []
  after_script: []

dependency_scanning:
  stage: validate
  before_script: []
  after_script: []

sast:
  before_script: []
  after_script: []

java_pmd:
  stage: test
  script:
    - cd android && ./gradlew :app:pmd
  artifacts:
    paths:
      - android/app/build/reports/pmd/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - android/build/
      - android/.gradle/
      - android/local.properties
      - android/app/build/
      - android/app/debug.keystore
      - node_modules/

java_lint_and_test:
  stage: test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run -d --device /dev/kvm --publish 8554:8554/tcp --publish 5555:5555/tcp $CI_REGISTRY_IMAGE:q-google-x86
    - adb connect localhost:5555
    - cd android && ./gradlew :app:connectedAndroidTest
  artifacts:
    paths:
      - android/app/build/reports/lint-results*.xml
      - android/app/build/reports/coverage/debug/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - android/build/
      - android/.gradle/
      - android/local.properties
      - android/app/build/
      - android/app/debug.keystore
      - node_modules/

python_validation_and_test:
  stage: test
  script:
    - cd android/app/src/main/python && nox && coverage html
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - android/app/src/main/python/htmlcov/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - __pycache__/
      - .pytest_cache/
      - .nox/
      - node_modules/
