before_script:
 - pip install nox
python-tests:
 image: python:3.8
 script:
  - echo "Running python unit tests…"
  - cd android/app/src/main/python
  - nox
  - coverage report
 coverage: '/^TOTAL.*\s+(\d+\%)$/'
