python-tests:
 before_script:
  - pip install nox
  - pip install libnacl
 image: python:3.8
 script:
  - echo "Running python unit tests…"
  - cd android/app/src/main/python
  - nox
  - coverage report
 coverage: '/^TOTAL.*\s+(\d+\%)$/'
