python-tests:
 before_script:
  - apt-get update
  - apt-get install libsodium-dev
  - pip install nox
 image: python:3.8
 script:
  - echo "Running python unit tests…"
  - cd android/app/src/main/python
  - nox
  - coverage report
 coverage: '/^TOTAL.*\s+(\d+\%)$/'
