#!/bin/bash

sec=0
timeout=60

err() {
	echo "$@"
}

while true; do
	if [[ $sec -ge $timeout ]]; then
		err "Timeout ($timeout seconds) reached - Failed to start emulator"
	fi
	out=$(docker ps 2>&1 | grep -v '^\*')
	let "r = sec % 5"
	if [[ $r -eq 0 ]]; then
		echo "Waiting for emulator to start: $out"
	fi
	sleep 1
	let "sec++"
done

echo "Emulator is ready"
