#!/bin/bash

sec=0
timeout=60

while true; do
	out=$(docker ps 2>&1 | grep -v '^\*')
	let "r = sec % 5"
	if [[ $r -eq 0 ]]; then
		echo "Waiting for emulator to start: $out"
	fi
	sleep 1
	let "sec++"
done

echo "Emulator is ready"
